// Generated by scripts/sync-registry.mjs from reviewed plugin manifests.
// Do not edit this file by hand.
export const plugins = [
  {
    "name": "cache_tier_selector",
    "description": "Buys the cheapest prompt-cache lifetime for a conversation based on how long it actually goes idle. Keeps each decision fixed until the provider cache tier expires, because changing a live breakpoint marker would invalidate the entry it is protecting.",
    "failureMode": "pass"
  },
  {
    "name": "cache_warmer",
    "description": "Keeps a chosen conversation's prompt cache alive across an idle gap. Opt-in per conversation and bounded by a deadline and a break-even refresh budget, because refreshing forever costs more than the cache miss it avoids.",
    "failureMode": "pass"
  },
  {
    "name": "compactor",
    "description": "Economically gated cheap-model tool-result compaction; uses cached intent when available and a bounded local fallback otherwise. Alternative to keyword_compactor — run ONE of the two; running after intent improves relevance.",
    "failureMode": "pass"
  },
  {
    "name": "intent",
    "description": "Captures WHY each tool call is made: injects the required 'i' field into tool schemas (plus a system-prompt example), extracts it from streamed tool calls into the shared cache, and strips it before the harness sees it. On later requests it rehydrates cached intents onto history tool calls (bridging them to the request's tool_call_ids for the compactors) and heuristically fills never-captured ones so no tool establishes an 'i'-less precedent. Run before keyword_compactor OR compactor — both consume the intent cache.",
    "failureMode": "pass"
  },
  {
    "name": "keyword_compactor",
    "description": "Deterministic keyword-based tool-result compaction; uses cached intent when available and a bounded local fallback otherwise. Alternative to compactor — run ONE of the two; running after intent improves relevance.",
    "failureMode": "pass"
  },
  {
    "name": "otel",
    "description": "OpenTelemetry per-request metrics: request shape on the way in; latency, status class, and token usage on the way out",
    "failureMode": "pass"
  },
  {
    "name": "pii",
    "description": "Scans tool results through a local model + regex pre-filter and blocks the request if PII is detected",
    "failureMode": "block"
  },
  {
    "name": "schema_translator",
    "description": "KV-array schema translation: converts additionalProperties maps to arrays on the way in and reverses on the stream",
    "failureMode": "pass"
  },
  {
    "name": "tool_governor",
    "description": "Restricts or replaces the tool definitions advertised to the model",
    "failureMode": "block"
  },
  {
    "name": "usage_logger",
    "description": "Write content-free request, latency, and token usage records to a rotating private JSONL file",
    "failureMode": "pass"
  }
] as const;
